export default {
  LOG_USER_IN_SUCCESS: 'LOG_USER_IN_SUCCESS',
  LOG_USER_IN_FAILURE: 'LOG_USER_IN_FAILURE',
  DISCONNECT_USER_SUCCESS: 'DISCONNECT_USER_SUCCESS',
  DISCONNECT_USER_FAILURE: 'DISCONNECT_USER_FAILURE'
}
