console.log('LUCIOLE REACTJS HELP')
console.log('--------------------')
console.log(' ** build : Build the app into dist')
console.log(' ** docs : generate documentation')
console.log(' ** lint:standard : launch standard linter')
console.log(' ** start : launch the app')
console.log(' ** test : launch the unit tests')
console.log(' ** test:cover : launch the unit tests + coverage')
console.log(' ** test:cover:travis : launch the unit tests + coverage + travis export')
console.log('--------------------')
